# Generated by Django 4.2.30 on 2026-05-24 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingestion', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel & Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], help_text='Which source produced this record', max_length=25)),
                ('source_identifier', models.CharField(blank=True, help_text='Original ID from source: PO number, meter ID, report ID', max_length=255)),
                ('ghg_scope', models.IntegerField(choices=[(1, 'Scope 1 - Direct'), (2, 'Scope 2 - Indirect Energy'), (3, 'Scope 3 - Other Indirect')])),
                ('ghg_category', models.CharField(help_text="e.g. 'Stationary Combustion', 'Purchased Electricity', 'Business Travel'", max_length=100)),
                ('activity_description', models.CharField(max_length=500)),
                ('activity_quantity', models.DecimalField(decimal_places=4, help_text='Quantity in normalized units', max_digits=14)),
                ('activity_unit', models.CharField(help_text='Normalized unit: L, kWh, passenger-km, room-night', max_length=30)),
                ('original_quantity', models.DecimalField(decimal_places=4, help_text='Quantity as originally reported in source', max_digits=14)),
                ('original_unit', models.CharField(help_text='Unit as it appeared in source data', max_length=30)),
                ('co2e_kg', models.DecimalField(decimal_places=4, help_text='Computed CO2 equivalent in kilograms', max_digits=14)),
                ('activity_date', models.DateField(blank=True, help_text='Specific date of activity, if known', null=True)),
                ('reporting_period_start', models.DateField(help_text='Start of the reporting/billing period')),
                ('reporting_period_end', models.DateField(help_text='End of the reporting/billing period')),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('facility_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged for Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False, help_text='True after approval — record becomes immutable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('quality_flags', models.JSONField(blank=True, default=list, help_text='e.g. ["estimated_reading", "unit_converted", "distance_derived"]')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('emission_factor', models.ForeignKey(blank=True, help_text='The factor used to compute CO2e', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.emissionfactor')),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.dataingestionjob')),
                ('raw_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_record', to='ingestion.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'review_status'], name='emissions_e_tenant__1dfd87_idx'), models.Index(fields=['tenant', 'ghg_scope'], name='emissions_e_tenant__95f0cf_idx'), models.Index(fields=['tenant', 'source_type'], name='emissions_e_tenant__2d142c_idx')],
            },
        ),
    ]
