# Generated by Django 4.2.30 on 2026-05-24 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ANALYST', 'Analyst')], default='ANALYST', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('FUEL_DIESEL', 'Diesel'), ('FUEL_PETROL', 'Petrol/Gasoline'), ('FUEL_NATURAL_GAS', 'Natural Gas'), ('FUEL_LPG', 'LPG'), ('ELECTRICITY_GRID', 'Grid Electricity'), ('FLIGHT_DOMESTIC', 'Domestic Flight'), ('FLIGHT_SHORT_HAUL', 'Short-Haul Flight'), ('FLIGHT_LONG_HAUL', 'Long-Haul Flight'), ('HOTEL', 'Hotel Stay'), ('CAR_RENTAL', 'Car Rental'), ('RAIL', 'Rail Travel'), ('TAXI', 'Taxi')], max_length=30)),
                ('unit_input', models.CharField(help_text="Input unit, e.g. 'L', 'kWh', 'passenger-km', 'room-night'", max_length=20)),
                ('unit_output', models.CharField(default='kg_co2e', max_length=20)),
                ('factor_value', models.DecimalField(decimal_places=6, help_text='kg CO2e per unit of input', max_digits=12)),
                ('source_reference', models.CharField(help_text="e.g. 'UK DESNZ 2024 - Table: Fuels'", max_length=255)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='NULL = system default; set tenant for client-specific overrides', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_factors', to='core.tenant')),
            ],
            options={
                'ordering': ['category', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=10)),
                ('plant_name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'plant_code')},
            },
        ),
    ]
